import {test,expect} from '@playwright/test';
const endpoint='https://formsubmit.co/ajax/project@cws.com';
async function fill(page){await page.getByLabel('Your name',{exact:true}).fill('Example Client');await page.getByLabel('Email address',{exact:true}).fill('client@example.test');await page.locator('textarea[name="message"]').fill('We need a clear website and an AI assistant for customer questions.');await page.getByRole('checkbox').check()}
test('public pages have no account navigation, arrows or backend requests on desktop and mobile',async({page})=>{
 const errors=[],api=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(new URL(r.url()).pathname.startsWith('/api/'))api.push(r.url())});
 for(const width of [1440,390]){await page.setViewportSize({width,height:900});for(const route of ['/','/about','/build','/book-a-meeting','/packages','/services/ai-agents-and-automation']){await page.goto(route);await expect(page.locator('h1')).toBeVisible();await expect(page.locator('a[href*="signup"],a[href*="login"],a[href*="portal"],a[href*="admin"],a[href*="preview"]')).toHaveCount(0);await expect(page.locator('.lucide-arrow-up-right,.lucide-arrow-right,.lucide-chevron-right,.lucide-chevron-left')).toHaveCount(0);expect(await page.locator('body').innerText()).not.toMatch(/[↗→←↑]/);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)}}expect(api).toEqual([]);expect(errors).toEqual([]);
});
test('old account routes are retired and old automation route redirects',async({page})=>{
 for(const route of ['/login','/signup','/admin','/portal','/preview/admin','/verify#token=obsolete']){await page.goto(route);await expect(page).toHaveURL(/\/contact$/);await expect(page.getByRole('form',{name:'General inquiry'})).toBeVisible()}
 await page.goto('/services/workflow-automation');await expect(page).toHaveURL(/ai-agents-and-automation$/);await expect(page.locator('h1')).toHaveText('AI Agents & Automation');await expect(page.getByRole('heading',{name:'What we deliver'})).toBeVisible();await page.locator('.service-brief-card').click();await expect(page.getByLabel('Service',{exact:true})).toHaveValue('AI Agents & Automation');
});
test('project form sends to the inbox endpoint, waits for acceptance and preserves failures',async({page})=>{
 let body;await page.route(endpoint,async route=>{body=route.request().postDataJSON();await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({success:false})})});await page.goto('/build?package=Business%20Growth');await expect(page.getByLabel('Starting package')).toHaveValue('Business Growth');await fill(page);await page.getByRole('button',{name:'Send inquiry',exact:true}).click();await expect(page.getByRole('alert')).toBeVisible();await expect(page.getByLabel('Your name',{exact:true})).toHaveValue('Example Client');await expect(page.getByText('REQUEST ACCEPTED',{exact:true})).toHaveCount(0);expect(body.email).toBe('client@example.test');expect(body.request_type).toBe('Project inquiry');
 await page.unroute(endpoint);let finish;await page.route(endpoint,async route=>{await new Promise(resolve=>finish=resolve);await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({success:'true'})})});await page.getByRole('button',{name:'Send inquiry',exact:true}).click();await expect(page.getByRole('button',{name:'Sending…'})).toBeDisabled();await expect(page.getByText('REQUEST ACCEPTED',{exact:true})).toHaveCount(0);finish();await expect(page.getByRole('heading',{name:'Thank you for getting in touch.'})).toBeVisible();
});
test('meeting request contains preferred time zone and does not claim a confirmed booking',async({page})=>{
 let body;await page.route(endpoint,async route=>{body=route.request().postDataJSON();await route.fulfill({status:200,contentType:'application/json',body:'{"success":true}'})});await page.goto('/book-a-meeting');await fill(page);await page.getByLabel('Preferred date',{exact:true}).fill('2099-01-01');await page.getByLabel('Preferred time',{exact:true}).fill('14:30');await page.getByLabel('Time zone',{exact:true}).fill('Africa/Nairobi');await page.getByRole('button',{name:'Request a meeting',exact:true}).click();await expect(page.getByRole('status')).toContainText('not a confirmed appointment');expect(body.preferred_date).toBe('2099-01-01');expect(body.time_zone).toBe('Africa/Nairobi');expect(body.request_type).toBe('Meeting request');
});
test('contact form reports inbox activation honestly and keeps the entered message',async({page})=>{
 await page.route(endpoint,route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({success:true,message:'Please activate your form'})}));await page.goto('/contact');await fill(page);await page.getByRole('button',{name:'Send inquiry',exact:true}).click();await expect(page.getByRole('alert')).toContainText('awaiting inbox activation');await expect(page.getByLabel('Email address',{exact:true})).toHaveValue('client@example.test');
});
test('about principles, photography, meeting navigation and clickable pricing work',async({page})=>{
 await page.goto('/about');await expect(page.locator('.principle-grid article')).toHaveCount(6);await expect(page.locator('.principle-grid')).toContainText('Responsible technology');for(const image of await page.locator('img').all()){await image.scrollIntoViewIfNeeded();await expect.poll(()=>image.evaluate(x=>x.complete&&x.naturalWidth>0)).toBe(true)}await page.locator('.about-invitation').getByRole('link',{name:'Book a meeting',exact:true}).click();await expect(page).toHaveURL(/book-a-meeting$/);await page.goto('/packages');await page.locator('.package-card').first().click({position:{x:30,y:30}});await expect(page).toHaveURL(/build\?package=Launch/);
 await page.goto('/');await page.getByRole('button',{name:'Next solution',exact:true}).click();await expect(page.locator('.journey-slide')).toContainText('Bring your store');await page.getByRole('button',{name:'Search CWS',exact:true}).click();await page.getByRole('textbox',{name:'Search services',exact:true}).fill('AI Agents');await page.locator('.search-results a').click();await expect(page).toHaveURL(/ai-agents-and-automation$/);
});
