import {test,expect} from '@playwright/test';
import {services,slug} from '../../shared/catalog.js';
test('public CRM preview filters, drills into clients and reconciles project balances',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/preview/admin');await expect(page.getByRole('heading',{name:'Analytics',exact:true})).toBeVisible();
 await page.getByRole('button',{name:/Clients with submissions/}).click();await expect(page.getByRole('heading',{name:'6 clients',exact:true})).toBeVisible();await page.getByLabel('Search CRM').fill('brian@example.test');await expect(page.locator('.crm-table-row')).toHaveCount(1);await page.locator('.crm-table-row').click();await page.getByRole('button',{name:'Account preview',exact:true}).click();await expect(page.getByRole('heading',{name:'Read-only client account preview'})).toBeVisible();await expect(page.locator('.crm-profile')).toContainText('DEMO-USER-002');await page.getByRole('button',{name:'Finance',exact:true}).last().click();await expect(page.locator('.crm-detail-row')).toContainText('20,000');
 await page.getByRole('navigation',{name:'Preview navigation'}).getByRole('button',{name:'Projects',exact:true}).click();await page.getByRole('button',{name:'Clear filters'}).click();await page.getByRole('button',{name:'Awaiting approval',exact:true}).click();await expect(page.locator('.crm-table-row')).toHaveCount(1);await expect(page.locator('.crm-table-row')).toContainText('brian@example.test');await expect(page.locator('.crm-table-row')).toContainText('20,000');await page.locator('.crm-table-row').click();await expect(page.getByRole('heading',{name:'Advisory website'})).toBeVisible();
 await page.getByRole('navigation',{name:'Preview navigation'}).getByRole('button',{name:'Finance',exact:true}).click();await page.getByLabel('Currency',{exact:true}).selectOption('USD');await expect(page.locator('.crm-finance-summary')).toContainText('$4,200');await expect(page.locator('.crm-finance-summary')).not.toContainText('KES');const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export filtered invoices'}).click();expect((await download).suggestedFilename()).toContain('invoices');
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);
});
test('every service has distinct content and photography, and the whole pricing card navigates',async({page})=>{
 const photos=new Set();for(const [name]of services){await page.goto('/services/'+slug(name));await expect(page.getByRole('heading',{level:1})).toHaveText(name);const img=page.locator('.page-intro img');await expect.poll(()=>img.evaluate(i=>i.complete&&i.naturalWidth>0)).toBe(true);photos.add(await img.getAttribute('src'));await expect(page.getByRole('heading',{name:'What we deliver'})).toBeVisible();await expect(page.locator('.service-detail-layout')).not.toContainText('Clear deliverables and an agreed scope')}
 expect(photos.size).toBe(12);await page.goto('/services/workflow-automation');await page.locator('.service-brief-card').click();await expect(page.getByLabel('Primary service')).toHaveValue('Workflow automation');
 await page.goto('/packages');expect(new Set(await page.locator('.package-card').evaluateAll(cards=>cards.map(c=>getComputedStyle(c).backgroundColor))).size).toBe(1);await expect(page.locator('.package-card a,.package-card button')).toHaveCount(0);await page.locator('.package-card').first().click({position:{x:30,y:30}});await expect(page).toHaveURL(/build\?package=Launch/);
 await page.goto('/');await expect(page.locator('body')).not.toContainText('+254 710');await expect(page.locator('img[src*="product.jpg"]')).toHaveCount(0);await expect(page.locator('.cloud-footer img')).toHaveAttribute('src','/brand/cws-logo-blue.png');await expect(page.locator('.journey-slide')).toHaveAttribute('href','/services/web-applications');await expect(page.locator('.journey-photo')).toBeVisible();
});
