import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';
async function login(page,email){await page.goto('/login');await page.getByLabel('Email address').fill(email);await page.getByRole('button',{name:'Email my sign-in link'}).click();await page.getByRole('link',{name:'Development only: open sign-in link'}).click()}
test('admin and client dashboards manage the same project with separate permissions',async({browser})=>{
 const adminContext=await browser.newContext(),clientContext=await browser.newContext();const admin=await adminContext.newPage(),client=await clientContext.newPage();const email=`dashboard-${Date.now()}@example.test`;
 try{
 const brief={business:{name:'Dashboard Studio',industry:'Technology',description:'Technology services for local business customers.',city:'Nairobi',country:'Kenya',contactName:'Dashboard Client',email,phone:'+254700123456',website:''},websiteType:'Corporate',package:'Business Growth',pages:['Home','Contact'],features:['Contact form'],style:'Technology',palette:'Blue',branding:'Existing identity',content:'Provide later',notes:'Please include product photos.',domain:'Need advice',domainName:'',hosting:'Need advice',emailService:'Not required',mailboxes:1,uploadIds:[],privacy:true};
 await client.goto('/');const result=await client.request.post('/api/briefs',{headers:{Origin:'http://localhost:5174','Idempotency-Key':randomUUID(),'X-Draft-Key':randomUUID()},data:brief});expect(result.status()).toBe(201);
 await login(admin,'project@cws.com');await expect(admin.getByRole('heading',{name:'Operations overview.'})).toBeVisible();await admin.getByRole('navigation',{name:'Workspace navigation'}).getByRole('button',{name:'Clients',exact:true}).click();await admin.getByRole('textbox',{name:'Search clients'}).fill(email);await expect(admin.locator('.client-row')).toHaveCount(1);await admin.locator('.client-row').filter({hasText:email}).click();await admin.locator('.dash-project').filter({hasText:'Dashboard Studio'}).click();await expect(admin.getByRole('heading',{name:'Project requirements & contact'})).toBeVisible();await admin.getByRole('tab',{name:'Tasks',exact:true}).click();await admin.getByLabel('Task title').fill('Upload approved copy');await admin.getByLabel('Assigned to').selectOption('Client');await admin.getByRole('button',{name:'Add task',exact:true}).click();await expect(admin.locator('.task-row')).toContainText('Upload approved copy');
 await admin.getByRole('tab',{name:'Team notes'}).click();await admin.getByLabel('Note',{exact:true}).fill('Private admin-only note');await admin.getByRole('button',{name:'Save internal note'}).click();await expect(admin.locator('.dash-note')).toContainText('Private admin-only note');
 await login(client,email);await expect(client.getByRole('heading',{name:'Your next chapter.'})).toBeVisible();await client.locator('.dash-project').filter({hasText:'Dashboard Studio'}).click();await expect(client.getByRole('tab',{name:'Team notes'})).toHaveCount(0);await client.getByRole('tab',{name:'Tasks',exact:true}).click();await client.getByLabel('Status of Upload approved copy').selectOption('Done');await expect(client.getByRole('status')).toContainText('Saved');
 await client.getByRole('navigation',{name:'Workspace navigation'}).getByRole('button',{name:'Account',exact:true}).click();await client.getByLabel('Your name').fill('Dashboard Client');await client.getByLabel('Company',{exact:true}).fill('Dashboard Studio');await client.getByRole('button',{name:'Save profile'}).click();await expect(client.getByRole('status')).toContainText('Profile saved.');
 for(const page of [admin,client]){await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)}
 }finally{await adminContext.close();await clientContext.close()}
});
