import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync,rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import { createApp } from '../server/app.js';
const origin='http://localhost:5173';
const sample=(email='client@example.test')=>({business:{name:'Test Studio',industry:'Architecture',description:'Architecture and interior design for local businesses.',city:'Nairobi',country:'Kenya',contactName:'Test Client',email,phone:'',website:''},websiteType:'Corporate',package:'Business Growth',pages:['Home','Contact'],features:['Contact form'],style:'Minimal',palette:'Forest & ivory',branding:'Existing identity',content:'Provide later',notes:'',domain:'Need advice',domainName:'',hosting:'Need advice',emailService:'Not required',mailboxes:1,uploadIds:[],privacy:true});
test('durable intake, verified identity, isolation, approval conflicts and payment idempotency',async t=>{
 const dir=mkdtempSync(join(tmpdir(),'cws-api-'));const {app,db}=createApp({dataDir:dir,origin,devLinks:true,admins:'owner@example.test'});const server=app.listen(0);await new Promise(r=>server.once('listening',r));const base=`http://127.0.0.1:${server.address().port}`;
 const call=async(path,{method='GET',body,cookie,headers={}}={})=>{const r=await fetch(base+'/api'+path,{method,headers:{Origin:origin,'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{}),...headers},body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};
 const login=async(email)=>{const r=await call('/auth/request',{method:'POST',body:{email}});assert.equal(r.status,200);const token=new URLSearchParams(new URL(r.data.developmentLink).hash.slice(1)).get('token');const v=await call('/auth/verify',{method:'POST',body:{token}});assert.equal(v.status,200);const twice=await call('/auth/verify',{method:'POST',body:{token}});assert.equal(twice.status,400);return v.cookie;};
 try{
  const key=randomUUID(),draft=randomUUID();const headers={'Idempotency-Key':key,'X-Draft-Key':draft};
  let r=await call('/briefs',{method:'POST',headers,body:sample()});assert.equal(r.status,201);const ref=r.data.reference;
  r=await call('/briefs',{method:'POST',headers,body:sample()});assert.equal(r.status,200);assert.equal(r.data.reference,ref);assert.equal(r.data.duplicate,true);
  r=await call('/briefs',{method:'POST',headers,body:sample('other@example.test')});assert.equal(r.status,409);
  assert.equal(db.prepare('SELECT COUNT(*) AS n FROM projects').get().n,1);assert.equal(db.prepare('SELECT COUNT(*) AS n FROM orders').get().n,1);assert.equal(db.prepare('SELECT COUNT(*) AS n FROM leads').get().n,1);
  const client=await login('client@example.test'),other=await login('other@example.test'),owner=await login('owner@example.test');
  assert.equal((await call('/projects')).status,401);
  const p=(await call('/projects',{cookie:client})).data.projects[0];assert.equal(p.reference,ref);assert.equal((await call('/projects',{cookie:other})).data.projects.length,0);
  assert.equal((await call('/projects/'+p.id,{cookie:other})).status,404);
  assert.equal((await call('/projects/'+p.id+'/messages',{method:'POST',cookie:other,body:{body:'Unauthorized'}})).status,404);
  assert.equal((await call('/admin/overview',{cookie:client})).status,403);
  assert.equal((await call('/projects/'+p.id,{method:'PATCH',cookie:client,body:{status:'Development',version:1,checks:[]}})).status,403);
  assert.equal((await call('/projects/'+p.id,{method:'PATCH',cookie:owner,body:{status:'Designing',version:1,checks:['Branding']}})).status,200);
  assert.equal((await call('/projects/'+p.id,{method:'PATCH',cookie:owner,body:{status:'Development',version:1,checks:[]}})).status,409);
  assert.equal((await call('/projects/'+p.id,{method:'PATCH',cookie:owner,body:{status:'Live',version:2,checks:[]}})).status,400);
  await call('/projects/'+p.id+'/deliverables',{method:'POST',cookie:owner,body:{title:'Homepage first design',url:'https://example.com/review'}});
  const d=(await call('/projects/'+p.id,{cookie:client})).data.deliverables[0];
  await call('/projects/'+p.id+'/deliverables',{method:'POST',cookie:owner,body:{title:'Homepage revised design',url:'https://example.com/review-v2'}});
  assert.equal((await call('/projects/'+p.id+'/approvals',{method:'POST',cookie:client,body:{id:d.id,status:'Approved'}})).status,409);
  const latest=(await call('/projects/'+p.id,{cookie:client})).data.deliverables[0];assert.equal((await call('/projects/'+p.id+'/approvals',{method:'POST',cookie:client,body:{id:latest.id,status:'Changes requested',feedback:''}})).status,400);
  assert.equal((await call('/projects/'+p.id+'/approvals',{method:'POST',cookie:client,body:{id:latest.id,status:'Approved'}})).status,200);
  await call('/projects/'+p.id+'/invoices',{method:'POST',cookie:owner,body:{description:'Agreed website scope',currency:'KES',total:100000}});
  const inv=(await call('/projects/'+p.id,{cookie:client})).data.invoices[0];const payment={amount:100000,reference:'VERIFIED-001'};
  assert.equal((await call('/invoices/'+inv.id+'/payments',{method:'POST',cookie:owner,body:payment})).status,200);
  assert.equal((await call('/invoices/'+inv.id+'/payments',{method:'POST',cookie:owner,body:payment})).data.duplicate,true);
  assert.equal(db.prepare('SELECT paid FROM invoices WHERE id=?').get(inv.id).paid,100000);
  assert.equal((await call('/invoices/'+inv.id+'/payments',{method:'POST',cookie:owner,body:{amount:1,reference:'OVERPAY'}})).status,409);
  assert.equal((await call('/contact',{method:'POST',headers:{Origin:'https://attacker.example'},body:{}})).status,403);
  assert.equal((await call('/briefs',{method:'POST',headers:{'Idempotency-Key':randomUUID(),'X-Draft-Key':draft},body:{...sample(),privacy:false}})).status,400);
  assert.ok(db.prepare('SELECT COUNT(*) AS n FROM outbox').get().n>0);
 }finally{await new Promise(r=>server.close(r));db.close();const restarted=createApp({dataDir:dir,origin});assert.equal(restarted.db.prepare('SELECT COUNT(*) AS n FROM projects').get().n,1);restarted.db.close();rmSync(dir,{recursive:true,force:true});}
});
