import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {createApp} from '../server/app.js';
const origin='http://localhost:5173';
test('workspace persistence, client isolation, task permissions, notes, support and account security',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'cws-workspace-'));const {app,db}=createApp({dataDir:dir,origin,devLinks:true,admins:'project@cws.com'});const server=app.listen(0);await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;
 const call=async(path,cookie,body,method=body?'POST':'GET')=>{const r=await fetch(base+'/api'+path,{method,headers:{Origin:origin,'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{})},body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]}};
 const login=async email=>{const l=await call('/auth/request',null,{email});const token=new URL(l.data.developmentLink).hash.slice(7);return (await call('/auth/verify',null,{token})).cookie};
 try{
  const owner=await login('project@cws.com'),client=await login('client@example.test'),other=await login('other@example.test');const pid=randomUUID(),stamp=new Date().toISOString();db.prepare('INSERT INTO projects(id,reference,email,name,brief,created,updated) VALUES(?,?,?,?,?,?,?)').run(pid,'CWS-TEST','client@example.test','Workspace test',JSON.stringify({business:{contactName:'Client'}}),stamp,stamp);
  assert.equal((await call('/dashboard')).status,401);assert.equal((await call('/dashboard',other)).data.counts.projects,0);assert.equal((await call('/dashboard',client)).data.counts.projects,1);assert.equal((await call('/admin/clients',client)).status,403);assert.equal((await call('/projects/'+pid+'/workspace',other)).status,404);
  const schedule={priority:'High',due_date:'2026-10-12',owner:'project@cws.com',version:0};assert.equal((await call('/projects/'+pid+'/schedule',client,schedule,'PATCH')).status,403);assert.equal((await call('/projects/'+pid+'/schedule',owner,{...schedule,due_date:'2026-02-31'},'PATCH')).status,400);assert.equal((await call('/projects/'+pid+'/schedule',owner,schedule,'PATCH')).status,200);assert.equal((await call('/projects/'+pid+'/schedule',owner,schedule,'PATCH')).status,409);
  assert.equal((await call('/projects/'+pid+'/tasks',client,{title:'Unauthorized',assignee:'Client'})).status,403);await call('/projects/'+pid+'/tasks',owner,{title:'Supply logo',assignee:'Client'});await call('/projects/'+pid+'/tasks',owner,{title:'Build pages',assignee:'Team'});
  let workspace=(await call('/projects/'+pid+'/workspace',client)).data;const ct=workspace.tasks.find(t=>t.assignee==='Client'),tt=workspace.tasks.find(t=>t.assignee==='Team');assert.equal((await call('/projects/'+pid+'/tasks/'+tt.id,client,{status:'Done',version:1},'PATCH')).status,403);assert.equal((await call('/projects/'+pid+'/tasks/'+ct.id,client,{status:'Done',version:1},'PATCH')).status,200);assert.equal((await call('/projects/'+pid+'/tasks/'+ct.id,client,{status:'Done',version:1},'PATCH')).status,409);
  await call('/projects/'+pid+'/notes',owner,{body:'Private commercial discussion'});workspace=(await call('/projects/'+pid+'/workspace',client)).data;assert.equal(workspace.notes.length,0);assert.ok(!JSON.stringify(workspace).includes('staff.note'));assert.equal((await call('/projects/'+pid+'/workspace',owner)).data.notes.length,1);
  await call('/profile',client,{name:'Verified Client',company:'Client Studio',phone:'+254700000000'},'PATCH');assert.equal((await call('/profile',client)).data.name,'Verified Client');assert.equal((await call('/admin/clients?search=Client%20Studio',owner)).data.total,1);
  await call('/tickets',client,{subject:'Need a content update',body:'Please help us update the homepage description.'});const ticket=(await call('/tickets',client)).data.tickets[0];assert.equal((await call('/tickets/'+ticket.id+'/conversation',other)).status,404);await call('/tickets/'+ticket.id,owner,{status:'Resolved'},'PATCH');await call('/tickets/'+ticket.id+'/replies',client,{body:'A further question, please.'});assert.equal((await call('/tickets/'+ticket.id+'/conversation',owner)).data.ticket.status,'Open');assert.equal((await call('/tickets/'+ticket.id+'/conversation',client)).data.replies.length,1);
  for(const c of ['KES','USD'])await call('/projects/'+pid+'/invoices',owner,{description:'Scoped service',currency:c,total:10000});assert.equal((await call('/dashboard',client)).data.billing.length,2);assert.equal((await call('/billing',other)).data.invoices.length,0);
  const client2=await login('client@example.test');await call('/profile/revoke-sessions',client,{});assert.equal((await call('/dashboard',client2)).status,401);assert.equal((await call('/dashboard',client)).status,200);
  await call('/projects/'+pid+'/deliverables',owner,{title:'Review this design',url:'https://example.com'});const d=(await call('/projects/'+pid,owner)).data.deliverables[0];assert.equal((await call('/projects/'+pid+'/approvals',owner,{id:d.id,status:'Approved'})).status,403);
 }finally{await new Promise(r=>server.close(r));db.close();const restarted=createApp({dataDir:dir,origin});assert.equal(restarted.db.prepare('SELECT COUNT(*) AS n FROM project_tasks').get().n,2);assert.equal(restarted.db.prepare('SELECT COUNT(*) AS n FROM schema_migrations').get().n,2);assert.equal(restarted.db.prepare('PRAGMA integrity_check').get().integrity_check,'ok');restarted.db.close();rmSync(dir,{recursive:true,force:true})}
});
