import {z} from 'zod';
import {reportCrm,enrichCrm,csvRows} from '../shared/crm.js';
const date=z.string().refine(v=>!v||(/^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v),'Invalid calendar date');
const filterSchema=z.object({asOf:date.optional(),cohort:z.enum(['','registered','submitted','active']).optional(),from:date.optional(),to:date.optional(),client:z.string().max(254).optional(),project:z.string().max(100).optional(),status:z.string().max(40).optional(),stage:z.string().max(40).optional(),service:z.string().max(100).optional(),package:z.string().max(100).optional(),payment:z.string().max(40).optional(),invoiceStatus:z.string().max(40).optional(),currency:z.string().max(3).optional(),search:z.string().max(100).optional()}).refine(v=>!v.from||!v.to||v.from<=v.to,'Start date must be before end date');
export function registerCrm(app,{db,auth,admin,admins,audit}){
 const q=s=>db.prepare(s);
 const raw=()=>({clients:q('SELECT u.id,u.email,u.name,u.created AS registered,p.company,p.phone,p.updated FROM users u LEFT JOIN profiles p ON p.user_id=u.id').all().filter(c=>!admins.includes(c.email)),projects:q(`SELECT p.*,m.priority,m.due_date,m.owner,EXISTS(SELECT 1 FROM deliverables d WHERE d.project_id=p.id AND d.status='Awaiting review' AND d.version=(SELECT MAX(version) FROM deliverables WHERE project_id=p.id)) AS awaiting_approval FROM projects p LEFT JOIN project_meta m ON m.project_id=p.id`).all().map(p=>({...p,brief:JSON.parse(p.brief)})),invoices:q('SELECT * FROM invoices').all(),payments:q('SELECT * FROM payments').all(),activity:q('SELECT actor AS email,created FROM audit').all()});
 app.get('/api/admin/crm',auth,admin,(req,res)=>res.json(reportCrm(raw(),filterSchema.parse(req.query))));
 app.get('/api/admin/crm/clients/:email',auth,admin,(req,res)=>{const email=z.string().email().parse(req.params.email),data=enrichCrm(raw()),client=data.clients.find(c=>c.email===email);if(!client)return res.status(404).json({error:'Client not found.'});const projects=data.projects.filter(p=>p.email===email),ids=new Set(projects.map(p=>p.id));res.json({client,projects,invoices:data.invoices.filter(i=>ids.has(i.project_id)),payments:data.payments.filter(p=>ids.has(p.invoice?.project_id)),messages:q('SELECT m.*,p.name AS project_name,u.name AS sender FROM messages m JOIN projects p ON p.id=m.project_id JOIN users u ON u.id=m.user_id WHERE p.email=? ORDER BY m.created DESC').all(email),tickets:q('SELECT * FROM tickets WHERE email=? ORDER BY created DESC').all(email),notes:q('SELECT n.*,p.name AS project_name,u.name AS author FROM staff_notes n JOIN projects p ON p.id=n.project_id JOIN users u ON u.id=n.user_id WHERE p.email=? ORDER BY n.created DESC').all(email),activity:q('SELECT action,created,entity FROM audit WHERE actor=? OR entity IN (SELECT id FROM projects WHERE email=?) ORDER BY id DESC LIMIT 100').all(email,email),readOnly:true})});
 app.patch('/api/admin/crm/invoices/:id',auth,admin,(req,res)=>{const v=z.object({due_date:date,version:z.number().int().min(1)}).parse(req.body);const row=q('SELECT * FROM invoices WHERE id=?').get(req.params.id);if(!row)return res.status(404).json({error:'Invoice not found.'});if(v.due_date&&v.due_date<row.created.slice(0,10))return res.status(400).json({error:'Due date cannot precede issue date.'});db.exec('BEGIN IMMEDIATE');try{const r=q('UPDATE invoices SET due_date=?,version=version+1 WHERE id=? AND version=?').run(v.due_date,row.id,v.version);if(!r.changes){db.exec('ROLLBACK');return res.status(409).json({error:'Invoice changed. Refresh and try again.'})}audit(req.user.email,'invoice.due_date.updated',row.id,{due_date:v.due_date});db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}res.json({ok:true})});
 app.get('/api/admin/crm/export/:kind',auth,admin,(req,res)=>{const r=reportCrm(raw(),filterSchema.parse(req.query));let rows;if(req.params.kind==='invoices')rows=[['Invoice ID','Client','Project','Issued UTC','Due date','Currency','Total minor units','Paid minor units','Outstanding minor units','Status'],...r.invoices.map(i=>[i.id,i.project.email,i.project.name,i.created,i.due_date,i.currency,i.total,i.paid,i.total-i.paid,i.status_label])];else if(req.params.kind==='payments')rows=[['Payment ID','Client','Project','Invoice','Recorded UTC','Reference','Currency','Amount minor units','Method'],...r.payments.map(p=>[p.id,p.invoice.project.email,p.invoice.project.name,p.invoice_id,p.created,p.reference,p.invoice.currency,p.amount,'Verified manual record'])];else return res.status(404).json({error:'Export not found.'});res.set('Content-Type','text/csv; charset=utf-8').set('Content-Disposition',`attachment; filename="cws-${req.params.kind}.csv"`).send('\uFEFF'+csvRows(rows))});
}
