import {z} from 'zod';
import {randomUUID,createHash} from 'node:crypto';
const now=()=>new Date().toISOString();
const fail=(status,message)=>Object.assign(new Error(message),{status});
const date=z.string().refine(v=>v===''||(/^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v),'Enter a valid date');
export function registerWorkspace(app,{db,auth,admin,project,serialize,audit,enqueue,admins,mailReady,devLinks}) {
 const q=sql=>db.prepare(sql);
 const scope=req=>req.user.role==='admin'?['',[]]:[' AND p.email=?',[req.user.email]];
 const transaction=fn=>{db.exec('BEGIN IMMEDIATE');try{const result=fn();db.exec('COMMIT');return result}catch(e){db.exec('ROLLBACK');throw e}};
 app.get('/api/dashboard',auth,(req,res)=>{
   const[filter,args]=scope(req);
   const projects=q('SELECT p.* FROM projects p WHERE 1=1'+filter+' ORDER BY p.updated DESC').all(...args);
   const billing=q('SELECT i.currency,SUM(i.total) AS total,SUM(i.paid) AS paid,SUM(i.total-i.paid) AS outstanding FROM invoices i JOIN projects p ON p.id=i.project_id WHERE 1=1'+filter+' GROUP BY i.currency').all(...args);
   const tasks=q("SELECT t.*,p.name AS project_name,p.reference FROM project_tasks t JOIN projects p ON p.id=t.project_id WHERE t.status!='Done'"+filter+" ORDER BY CASE WHEN t.due_date='' THEN 1 ELSE 0 END,t.due_date,t.created LIMIT 8").all(...args);
   const approvals=q("SELECT d.*,p.name AS project_name FROM deliverables d JOIN projects p ON p.id=d.project_id WHERE d.status='Awaiting review' AND d.version=(SELECT MAX(version) FROM deliverables WHERE project_id=p.id)"+filter+' ORDER BY d.created DESC LIMIT 8').all(...args);
   const messages=q('SELECT m.id,m.project_id,m.body,m.created,u.name AS sender,p.name AS project_name FROM messages m JOIN projects p ON p.id=m.project_id JOIN users u ON u.id=m.user_id WHERE 1=1'+filter+' ORDER BY m.created DESC LIMIT 5').all(...args);
   const reviewCount=q("SELECT COUNT(*) AS n FROM deliverables d JOIN projects p ON p.id=d.project_id WHERE d.status='Awaiting review' AND d.version=(SELECT MAX(version) FROM deliverables WHERE project_id=p.id)"+filter).get(...args).n;
   const states=projects.reduce((out,p)=>({...out,[p.status]:(out[p.status]||0)+1}),{});
   const ticketCount=req.user.role==='admin'?q("SELECT COUNT(*) AS n FROM tickets WHERE status!='Resolved'").get().n:q("SELECT COUNT(*) AS n FROM tickets WHERE status!='Resolved' AND email=?").get(req.user.email).n;
   res.json({counts:{projects:projects.length,active:projects.filter(p=>!['Live','Cancelled','On hold'].includes(p.status)).length,review:reviewCount,openTickets:ticketCount},states,billing,tasks,approvals,messages,recent:projects.slice(0,5).map(serialize),system:req.user.role==='admin'?{database:'Connected',schemaVersion:q('SELECT MAX(version) AS v FROM schema_migrations').get().v,email:mailReady?'Configured':devLinks?'Development only':'Not configured',uploads:'Quarantined',payments:'Manual records'}:undefined});
 });
 app.get('/api/billing',auth,(req,res)=>{const[f,a]=scope(req);res.json({invoices:q('SELECT i.*,p.name AS project_name,p.reference FROM invoices i JOIN projects p ON p.id=i.project_id WHERE 1=1'+f+' ORDER BY i.created DESC').all(...a)})});
 app.get('/api/admin/clients',auth,admin,(req,res)=>{
   const search=String(req.query.search||'').slice(0,100).toLowerCase(),page=Math.max(1,Math.min(100000,Number.parseInt(req.query.page)||1)),size=20;
   const base=`WITH identities AS (SELECT email FROM users UNION SELECT email FROM projects), clients AS (SELECT e.email,COALESCE(u.name,(SELECT json_extract(brief,'$.business.contactName') FROM projects WHERE email=e.email ORDER BY created DESC LIMIT 1),'Client') AS name,COALESCE(pr.company,'') AS company,COALESCE(pr.phone,'') AS phone,u.created AS registered,(SELECT COUNT(*) FROM projects WHERE email=e.email) AS projects FROM identities e LEFT JOIN users u ON u.email=e.email LEFT JOIN profiles pr ON pr.user_id=u.id) `;
   const like='%'+search+'%';const where=' WHERE lower(name||email||company) LIKE ?';
   const total=q(base+'SELECT COUNT(*) AS n FROM clients'+where).get(like).n;
   res.json({clients:q(base+'SELECT * FROM clients'+where+' ORDER BY name,email LIMIT ? OFFSET ?').all(like,size,(page-1)*size),total,page,pages:Math.max(1,Math.ceil(total/size))});
 });
 app.get('/api/admin/clients/:email',auth,admin,(req,res)=>{const email=z.string().email().parse(req.params.email).toLowerCase();const user=q('SELECT name,email,created FROM users WHERE email=?').get(email);const projects=q('SELECT * FROM projects WHERE email=? ORDER BY created DESC').all(email);if(!user&&!projects.length)throw fail(404,'Client not found.');res.json({client:user||{email,name:JSON.parse(projects[0].brief).business.contactName},projects:projects.map(serialize)})});
 app.get('/api/projects/:id/workspace',auth,(req,res)=>{const p=project(req);res.json({meta:q('SELECT * FROM project_meta WHERE project_id=?').get(p.id)||{priority:'Normal',due_date:'',owner:'',version:0},tasks:q('SELECT * FROM project_tasks WHERE project_id=? ORDER BY created').all(p.id),notes:req.user.role==='admin'?q('SELECT n.*,u.name FROM staff_notes n JOIN users u ON u.id=n.user_id WHERE project_id=? ORDER BY n.created DESC').all(p.id):[],activity:q("SELECT action,created FROM audit WHERE entity=? AND action IN ('brief.submitted','project.updated','project.scheduled','task.created','task.updated','deliverable.reviewed','invoice.created') ORDER BY id DESC LIMIT 30").all(p.id)})});
 app.patch('/api/projects/:id/schedule',auth,admin,(req,res)=>{const p=project(req);const v=z.object({priority:z.enum(['Low','Normal','High','Urgent']),due_date:date,owner:z.string().trim().max(254),version:z.number().int().min(0)}).parse(req.body);if(v.owner&&!admins.includes(v.owner.toLowerCase()))throw fail(400,'Assign a configured administrator email.');transaction(()=>{const existing=q('SELECT * FROM project_meta WHERE project_id=?').get(p.id);if((existing?.version||0)!==v.version)throw fail(409,'Schedule changed. Refresh before saving.');q('INSERT INTO project_meta(project_id,priority,due_date,owner,version) VALUES(?,?,?,?,1) ON CONFLICT(project_id) DO UPDATE SET priority=excluded.priority,due_date=excluded.due_date,owner=excluded.owner,version=project_meta.version+1').run(p.id,v.priority,v.due_date,v.owner.toLowerCase());audit(req.user.email,'project.scheduled',p.id);});res.json({ok:true})});
 app.post('/api/projects/:id/tasks',auth,admin,(req,res)=>{const p=project(req);const v=z.object({title:z.string().trim().min(3).max(200),assignee:z.enum(['Team','Client']),due_date:date.default('')}).parse(req.body);transaction(()=>{q('INSERT INTO project_tasks(id,project_id,title,assignee,due_date,created,updated) VALUES(?,?,?,?,?,?,?)').run(randomUUID(),p.id,v.title,v.assignee,v.due_date,now(),now());audit(req.user.email,'task.created',p.id);});res.status(201).json({ok:true})});
 app.patch('/api/projects/:id/tasks/:task',auth,(req,res)=>{const p=project(req);const task=q('SELECT * FROM project_tasks WHERE id=? AND project_id=?').get(req.params.task,p.id);if(!task)throw fail(404,'Task not found.');if(req.user.role!=='admin'&&task.assignee!=='Client')throw fail(403,'Only CWS can update team tasks.');const v=z.object({status:z.enum(['Open','In progress','Done']),version:z.number().int()}).parse(req.body);transaction(()=>{if(!q('UPDATE project_tasks SET status=?,version=version+1,updated=? WHERE id=? AND version=?').run(v.status,now(),task.id,v.version).changes)throw fail(409,'Task changed. Refresh before saving.');audit(req.user.email,'task.updated',p.id,{task:task.id,status:v.status});});res.json({ok:true})});
 app.post('/api/projects/:id/notes',auth,admin,(req,res)=>{const p=project(req);const {body}=z.object({body:z.string().trim().min(1).max(3000)}).parse(req.body);q('INSERT INTO staff_notes VALUES(?,?,?,?,?)').run(randomUUID(),p.id,req.user.id,body,now());audit(req.user.email,'staff.note.added',p.id);res.status(201).json({ok:true})});
 const ticket=req=>{const t=q('SELECT * FROM tickets WHERE id=?').get(req.params.ticket);if(!t||(req.user.role!=='admin'&&t.email!==req.user.email))throw fail(404,'Support request not found.');return t};
 app.get('/api/tickets/:ticket/conversation',auth,(req,res)=>{const t=ticket(req);res.json({ticket:t,replies:q('SELECT r.id,r.body,r.created,u.name FROM ticket_replies r JOIN users u ON u.id=r.user_id WHERE ticket_id=? ORDER BY r.created').all(t.id)})});
 app.post('/api/tickets/:ticket/replies',auth,(req,res)=>{const t=ticket(req);const {body}=z.object({body:z.string().trim().min(1).max(3000)}).parse(req.body);transaction(()=>{q('INSERT INTO ticket_replies VALUES(?,?,?,?,?)').run(randomUUID(),t.id,req.user.id,body,now());if(t.status==='Resolved')q("UPDATE tickets SET status='Open' WHERE id=?").run(t.id);enqueue(req.user.role==='admin'?t.email:process.env.STAFF_EMAIL,'CWS support reply','A new reply is available in your CWS support workspace.');audit(req.user.email,'ticket.replied',t.id);});res.status(201).json({ok:true})});
 app.get('/api/profile',auth,(req,res)=>res.json({name:req.user.name,email:req.user.email,...(q('SELECT company,phone FROM profiles WHERE user_id=?').get(req.user.id)||{company:'',phone:''})}));
 app.patch('/api/profile',auth,(req,res)=>{const v=z.object({name:z.string().trim().min(2).max(100),company:z.string().trim().max(120),phone:z.string().trim().max(30)}).parse(req.body);transaction(()=>{q('UPDATE users SET name=? WHERE id=?').run(v.name,req.user.id);q('INSERT INTO profiles VALUES(?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET company=excluded.company,phone=excluded.phone,updated=excluded.updated').run(req.user.id,v.company,v.phone,now());audit(req.user.email,'profile.updated',req.user.id);});res.json({ok:true})});
 app.post('/api/profile/revoke-sessions',auth,(req,res)=>{const token=req.headers.cookie?.split(';').map(x=>x.trim()).find(x=>x.startsWith('cws_session='))?.slice(12);const digest=createHash('sha256').update(token).digest('hex');q('DELETE FROM sessions WHERE user_id=? AND hash!=?').run(req.user.id,digest);audit(req.user.email,'sessions.revoked',req.user.id);res.json({ok:true})});
}
