import {services,packages} from './catalog.js';
// Fictional records for the public preview only. Never sent to the API.
const stamp=(month,day=10)=>`2026-${String(month).padStart(2,'0')}-${String(day).padStart(2,'0')}T10:30:00.000Z`;
export const crmDemo={clients:[['Amina Demo','Example Retail','amina@example.test',6],['Brian Demo','Example Advisory','brian@example.test',7],['Caro Demo','Example Logistics','caro@example.test',8],['David Demo','Example Studio','david@example.test',9],['Esther Demo','Example Learning','esther@example.test',9],['Farah Demo','Example Wellness','farah@example.test',8]].map(([name,company,email,m],i)=>({id:'DEMO-USER-'+String(i+1).padStart(3,'0'),name,company,email,registered:stamp(m,3+i),phone:'',updated:stamp(9,10+i)})),projects:[],invoices:[],payments:[],activity:[]};
const specifications=[['Online retail launch',0,'Development',65,2,2,7],['Advisory website',1,'Client Review',80,0,1,8],['Dispatch operations',2,'Assigned',15,3,3,9],['Brand identity refresh',3,'New',0,8,0,9],['Learning platform',4,'Live',100,1,3,6],['Booking experience',5,'On hold',35,4,1,8],['Workflow handover',2,'Ready',95,7,3,8],['Campaign landing page',1,'Cancelled',0,0,0,7]];
crmDemo.projects=specifications.map(([name,c,status,progress,s,p,m],i)=>({id:'DEMO-PROJECT-'+(i+1),reference:'DEMO-2026-'+String(i+1).padStart(3,'0'),email:crmDemo.clients[c].email,name,status,progress,created:stamp(m,10+i),updated:stamp(9,20+i),due_date:stamp(10,5+i).slice(0,10),priority:i===1?'High':'Normal',owner:'Demo delivery team',brief:{service:services[s][0],package:packages[p].name,websiteType:s===2?'E-commerce':s===1?'Custom':'Corporate',business:{name:crmDemo.clients[c].company,contactName:crmDemo.clients[c].name,email:crmDemo.clients[c].email,phone:'',description:`Sample brief for ${name.toLowerCase()}. Organise customer information, provide clear next steps and make everyday tasks easier.`,industry:'Business services',city:'Nairobi',country:'Kenya'},pages:['Home','Services','Contact'],features:['Contact form','Analytics'],style:'Technology',palette:'Blue',domain:'CWS domain assistance',hosting:'CWS managed hosting',notes:'Fictional project for exploring the CWS preview.'}}));
crmDemo.invoices=[['Retail build deposit',0,'KES',8000000,3000000,7],['Website delivery',1,'KES',4500000,2500000,8],['Operations discovery',2,'KES',2000000,0,9],['Learning platform build',4,'USD',300000,300000,6],['Booking prototype',5,'KES',1500000,500000,8],['Automation handover',6,'USD',120000,50000,9]].map(([description,p,currency,total,paid,m],i)=>({id:'DEMO-INVOICE-'+(i+1),project_id:crmDemo.projects[p].id,description,currency,total,paid,status:paid>=total?'Paid':paid?'Partially paid':'Unpaid',created:stamp(m,18),due_date:stamp(m===9?10:m+1,18).slice(0,10),version:1}));
crmDemo.payments=crmDemo.invoices.filter(i=>i.paid>0).map((i,n)=>({id:'DEMO-PAYMENT-'+(n+1),invoice_id:i.id,amount:i.paid,reference:'SAMPLE-TRANSFER-'+String(n+1).padStart(3,'0'),created:stamp(Math.min(9,Number(i.created.slice(5,7))+1),21)}));
crmDemo.activity=crmDemo.clients.map(c=>({email:c.email,created:c.updated,action:'sample.account.updated'}));
crmDemo.messages=[{id:'demo-message',project_id:crmDemo.projects[1].id,sender:'CWS demo team',project_name:crmDemo.projects[1].name,body:'The homepage is ready for your review. Please confirm the approved copy.',created:stamp(9,25)}];
crmDemo.notes=[{id:'demo-note',project_id:crmDemo.projects[1].id,project_name:crmDemo.projects[1].name,author:'Demo administrator',body:'Confirm launch date after the content review.',created:stamp(9,24)}];
crmDemo.tickets=[{id:'demo-ticket',email:crmDemo.clients[1].email,subject:'Sample content question',body:'Where should we provide the updated service descriptions?',status:'Open',created:stamp(9,25)}];
// A registered account with no brief makes the onboarding distinction visible.
crmDemo.clients.push({id:'DEMO-USER-007',name:'Grace Demo',company:'Example Ventures',email:'grace@example.test',registered:stamp(9,28),updated:stamp(9,28),phone:''});
