import React,{useState,useEffect,useRef} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {ArrowRight,ArrowLeft,Check,Upload,ShieldCheck,X,CheckCircle2,RotateCcw,LockKeyhole} from 'lucide-react';
import {stages,types,features,styles,packages} from '../shared/catalog.js';
import {businessSchema,briefSchema,estimate} from '../shared/validation.js';
import {api} from './api.js';
const KEY='cws-brief-v1';
const defaults={business:{name:'',industry:'',description:'',city:'',country:'',contactName:'',email:'',phone:'',website:''},websiteType:'Corporate',package:'CWS Business',pages:['Home','About','Services','Contact'],features:['Contact form'],style:'Minimal',palette:'Forest & ivory',branding:'Existing identity',content:'Provide later',notes:'',domain:'Need advice',domainName:'',hosting:'Need advice',emailService:'Not required',mailboxes:1,uploadIds:[],privacy:false};
function saved(){try{const v=JSON.parse(localStorage.getItem(KEY));return v&&Date.now()-v.time<30*86400000?v:null}catch{return null}}
function Choices({values,value,onChange,multi=false,visual=false}){return <div className={`choices ${visual?'visual-choices':''}`}>{values.map((v,i)=><button key={v} type="button" className={`choice ${visual?'style-'+i:''} ${(multi?value.includes(v):value===v)?'selected':''}`} aria-pressed={multi?value.includes(v):value===v} onClick={()=>onChange(multi?(value.includes(v)?value.filter(x=>x!==v):[...value,v]):v)}>{visual&&<div className="style-sample"><i/><span>Aa</span><div/></div>}<span>{v}</span><span className="selection-mark">{(multi?value.includes(v):value===v)&&<Check size={13}/>}</span></button>)}</div>}
export default function Builder(){
  const[params]=useSearchParams();const initial=useRef(saved());
  const[data,setData]=useState(()=>({...defaults,...initial.current?.data,package:packages.some(p=>p.name===params.get('package'))?params.get('package'):(initial.current?.data.package||defaults.package),uploadIds:[],privacy:false}));
  const[step,setStep]=useState(initial.current?.step||0),[error,setError]=useState(''),[fields,setFields]=useState([]),[busy,setBusy]=useState(false),[receipt,setReceipt]=useState(null),[files,setFiles]=useState([]),[uploading,setUploading]=useState(false),[newPage,setNewPage]=useState('');
  const draftKey=useRef(initial.current?.draftKey||crypto.randomUUID()),submissionKey=useRef(crypto.randomUUID()),heading=useRef(null);
  const update=(k,v)=>setData(d=>({...d,[k]:v}));const business=(k,v)=>setData(d=>({...d,business:{...d.business,[k]:v}}));
  useEffect(()=>{if(!receipt){const {business:identity,...rest}=data;try{localStorage.setItem(KEY,JSON.stringify({time:Date.now(),step,draftKey:draftKey.current,data:{...rest,uploadIds:[],privacy:false,business:{...identity,contactName:'',email:'',phone:''}}}))}catch{}}},[data,step,receipt]);
  useEffect(()=>heading.current?.focus(),[step]);
  function next(){setError('');setFields([]);if(step===0){const v=businessSchema.safeParse(data.business);if(!v.success){setError('Please check your business and contact details.');setFields(v.error.errors.map(e=>({path:'business.'+e.path.join('.'),message:e.message})));return;}}if(step===2&&!data.pages.length){setError('Choose at least one page.');return;}if(step===6&&data.domain==='Existing domain'&&!/^(?:[a-z0-9-]+\.)+[a-z]{2,}$/i.test(data.domainName)){setError('Enter a valid existing domain, such as yourbusiness.com.');return;}setStep(s=>Math.min(7,s+1));}
  async function submit(){setError('');setFields([]);const payload={...data,uploadIds:files.map(f=>f.id)};const parsed=briefSchema.safeParse(payload);if(!parsed.success){setError('Please review the required details before submitting.');setFields(parsed.error.errors.map(e=>({path:e.path.join('.'),message:e.message})));return;}setBusy(true);try{const r=await api('/briefs',{method:'POST',headers:{'Idempotency-Key':submissionKey.current,'X-Draft-Key':draftKey.current},body:payload});setReceipt(r.reference);localStorage.removeItem(KEY);}catch(e){setError(e.message);setFields(e.fields||[])}finally{setBusy(false)}}
  async function upload(e){setUploading(true);setError('');for(const file of e.target.files){const body=new FormData();body.append('file',file);try{const r=await api('/uploads',{method:'POST',headers:{'X-Draft-Key':draftKey.current},body});setFiles(f=>[...f,r]);}catch(e){setError(e.message);break;}}setUploading(false);e.target.value='';}
  const input=(name,label,opts={})=><label key={name}>{label}{opts.optional&&<small>Optional</small>}<input value={data.business[name]} onChange={e=>business(name,e.target.value)} {...opts} optional={undefined} aria-invalid={fields.some(f=>f.path==='business.'+name)}/></label>;
  if(receipt)return <section className="receipt"><CheckCircle2 size={54}/><span className="eyebrow">A GREAT START</span><h1>Your brief is in.<br/><em>Let’s make it happen.</em></h1><p>Your project has been saved. CWS will review the scope and next steps before work begins.</p><div className="receipt-reference"><span>YOUR PROJECT REFERENCE</span><strong>{receipt}</strong></div><p>Sign in with <b>{data.business.email}</b> to follow your project.</p><Link className="button" to="/login">Go to your project portal <ArrowRight size={18}/></Link><button className="button secondary" onClick={()=>window.print()}>Print receipt</button></section>;
  return <div className="builder"><aside className="builder-aside"><Link to="/" className="back-link"><ArrowLeft size={15}/>Back to CWS</Link><h2>Let’s build <br/>something <br/><em>exceptional.</em></h2><p>A little about your business.<br/>A big step toward what’s next.</p><ol className="stage-list">{stages.map((s,i)=><li key={s} className={i===step?'current':i<step?'complete':''}><button disabled={i>step} onClick={()=>{setStep(i);setError('')}}><span>{i<step?<Check size={14}/>:String(i+1).padStart(2,'0')}</span>{s}</button></li>)}</ol><div className="builder-trust"><ShieldCheck size={19}/><span>No payment required to submit.<br/>Your quote comes before commitment.</span></div></aside><section className="builder-main"><div className="builder-top"><span>STEP {step+1} OF 8</span><span>YOUR VISION, TAKING SHAPE</span></div><div className="progress-track"><span style={{width:`${(step+1)/8*100}%`}}/></div><div className="step-heading"><span className="small-label">{stages[step]}</span><h1 ref={heading} tabIndex={-1}>{['First, tell us about you.','What are we building?','Make room for your ideas.','What feels like your brand?','A signature that’s yours.','Bring your story with you.','A home on the internet.','Your vision, all together.'][step]}</h1><p>{['The essentials help us understand your business and reach the right person.','Choose the closest fit. We’ll help shape the details.','Select your pages and the things your website needs to do.','A visual starting point. We’ll make it distinctly yours.','Bring your identity, or let us help you create one.','Have your content ready? Share it. Need a hand? We can help.','Let us know what you have and what you need.','Check the details. You can edit any section before sending.'][step]}</p></div>
    {error&&<div className="error-summary" role="alert">{error}{fields.length>0&&<ul>{fields.map((f,i)=><li key={i}>{f.path.replace('business.','')}: {f.message}</li>)}</ul>}</div>}
    <div className="step-content">
    {step===0&&<div className="fields-grid">{input('name','Business name',{maxLength:120})}{input('industry','Industry',{maxLength:100,placeholder:'e.g. Hospitality, retail, consulting'})}<label className="full">What does your business do?<textarea value={data.business.description} onChange={e=>business('description',e.target.value)} minLength={20} maxLength={2000} rows={3} placeholder="Tell us what you offer and who you serve."/></label>{input('city','City')}{input('country','Country')}{input('contactName','Your name',{autoComplete:'name'})}{input('email','Email address',{type:'email',autoComplete:'email'})}{input('phone','Phone or WhatsApp',{type:'tel',optional:true,placeholder:'+254…'})}{input('website','Existing website',{type:'url',optional:true,placeholder:'https://'})}<p className="hint full">Contact details stay in this session and are not saved to your browser’s draft storage.</p></div>}
    {step===1&&<><Choices values={types} value={data.websiteType} onChange={v=>update('websiteType',v)}/><h3 className="field-heading">Choose your starting package</h3><select aria-label="Package" value={data.package} onChange={e=>update('package',e.target.value)}>{packages.map(p=><option key={p.name}>{p.name}</option>)}</select><p className="hint">Every package receives a personalized quote. You can change this during review.</p></>}
    {step===2&&<><h3 className="field-heading">Your pages</h3><Choices values={[...new Set(['Home','About','Services','Work','Contact','Blog','Shop',...data.pages])]} value={data.pages} onChange={v=>update('pages',v)} multi/><div className="inline-input"><input aria-label="Custom page name" value={newPage} maxLength={60} onChange={e=>setNewPage(e.target.value)} placeholder="Add another page"/><button type="button" className="button secondary" disabled={!newPage.trim()||data.pages.length>=20} onClick={()=>{update('pages',[...new Set([...data.pages,newPage.trim()])]);setNewPage('')}}>Add</button></div><h3 className="field-heading">Features & integrations</h3><Choices values={features} value={data.features} onChange={v=>update('features',v)} multi/></>}
    {step===3&&<><Choices values={[...styles,'Guide me']} value={data.style} onChange={v=>update('style',v)} visual/><h3 className="field-heading">Color direction</h3><Choices values={['Forest & ivory','Monochrome','Warm neutrals','Bold & vibrant','Use my existing brand']} value={data.palette} onChange={v=>update('palette',v)}/></>}
    {step===4&&<><Choices values={['Existing identity','New logo','Full brand identity','Refresh identity']} value={data.branding} onChange={v=>update('branding',v)}/><div className="explanation"><PenIcon/><h3>More than a logo.</h3><p>A full identity brings your logo, color palette and typography together. We’ll include the exact deliverables and revision allowance in your quote.</p></div></>}
    {step===5&&<><Choices values={['Ready','Provide later','Create content for me']} value={data.content} onChange={v=>update('content',v)}/><label className="upload-zone"><Upload/><b>{uploading?'Uploading…':'Share what you have'}</b><span>PNG, JPG, WEBP, PDF or TXT · 20 MB each</span><input type="file" multiple accept=".png,.jpg,.jpeg,.webp,.pdf,.txt" onChange={upload} disabled={uploading||files.length>=10}/></label><p className="hint">Files are stored privately in quarantine. Downloads remain locked until security scanning is configured. You can submit without attachments.</p>{files.map(f=><div className="upload-row" key={f.id}><span>{f.name}<small>{Math.ceil(f.size/1024)} KB · Quarantined</small></span><button aria-label={`Remove ${f.name}`} onClick={()=>setFiles(files.filter(x=>x.id!==f.id))}><X size={17}/></button></div>)}<label>Anything else we should know?<textarea rows={3} maxLength={3000} value={data.notes} onChange={e=>update('notes',e.target.value)}/></label></>}
    {step===6&&<><h3 className="field-heading">Your domain</h3><Choices values={['Existing domain','CWS domain assistance','Need advice']} value={data.domain} onChange={v=>update('domain',v)}/>{data.domain==='Existing domain'&&<label>Domain name<input value={data.domainName} onChange={e=>update('domainName',e.target.value)} placeholder="yourbusiness.com"/></label>}<p className="hint">Domain availability has not been checked. We’ll confirm ownership and next steps.</p><h3 className="field-heading">Hosting</h3><Choices values={['Existing hosting','CWS managed hosting','Need advice']} value={data.hosting} onChange={v=>update('hosting',v)}/><h3 className="field-heading">Business email</h3><Choices values={['Existing email','New professional email','Not required']} value={data.emailService} onChange={v=>update('emailService',v)}/>{data.emailService==='New professional email'&&<label>Mailboxes<input type="number" min={1} max={100} value={data.mailboxes} onChange={e=>update('mailboxes',Number(e.target.value))}/></label>}<p className="hint"><LockKeyhole size={13}/>Never share account passwords here. Access is arranged securely during onboarding.</p></>}
    {step===7&&<><div className="review-grid">{[['Your business',`${data.business.name} · ${data.business.industry}`,`${data.business.contactName} · ${data.business.email}`,0],['Website',`${data.websiteType} · ${data.package}`,data.pages.join(', '),1],['Features',data.features.join(', ')||'No extra features','',2],['Design',data.style,data.palette,3],['Branding',data.branding,'',4],['Content',data.content,`${files.length} attached file(s)`,5],['Domain & hosting',`${data.domain} · ${data.hosting}`,data.emailService,6]].map(([label,value,sub,index])=><div className="review-row" key={label}><div><span>{label}</span><strong>{value}</strong>{sub&&<p>{sub}</p>}</div><button onClick={()=>setStep(index)}>Edit</button></div>)}</div><div className="quote-summary"><span>YOUR NEXT STEP</span><h3>A personalized quote.</h3><p>{estimate(data).reason} Final scope, one-time fees and recurring services are confirmed before work starts.</p></div><label className="check-label"><input type="checkbox" checked={data.privacy} onChange={e=>update('privacy',e.target.checked)}/>I have read the <Link to="/privacy">privacy notice</Link> and understand this is a quote request.</label></>}
    </div><div className="builder-bottom"><button className="back-link" disabled={step===0||busy} onClick={()=>{setStep(s=>s-1);setError('')}}><ArrowLeft size={16}/>Back</button><span className="saved">Draft saved on this device</span>{step<7?<button className="button" onClick={next}>Continue<ArrowRight size={18}/></button>:<button className="button" disabled={busy||uploading} onClick={submit}>{busy?'Saving your brief…':'Submit my project brief'}<ArrowRight size={18}/></button>}</div><button className="reset-draft" onClick={()=>{if(window.confirm('Clear this draft and start again?')){setData(defaults);setFiles([]);setStep(0);localStorage.removeItem(KEY);draftKey.current=crypto.randomUUID();submissionKey.current=crypto.randomUUID();}}}><RotateCcw size={12}/>Reset draft</button></section></div>
}
function PenIcon(){return <span className="identity-symbol">Aa<span>↗</span></span>}
