import React,{useState} from 'react';
import {Link} from 'react-router-dom';
import {Cloud,Database,ShieldCheck,Workflow,Code2,BarChart3} from 'lucide-react';
const journeyPhotos=['/images/sections/customer.jpg','/images/sections/store.jpg','/images/sections/operations.jpg','/images/sections/identity.jpg','/images/sections/support.jpg'];
const journeyAlts=['Colleagues discussing a customer project','Clothing displays in a retail shop','Analytics charts on a laptop screen','Design workspace with typography and interface layouts','Colleagues reviewing work at office computers'];
const journeys=[{title:'Give your customers a better way to connect.',label:'CUSTOMER EXPERIENCE',text:'A website, a booking flow or a customer portal. Bring the information and actions your customers need into one clear journey.',to:'/services/web-applications',icon:Code2},{title:'Bring your store and payments together.',label:'COMMERCE',text:'Make it easier to discover products, place orders and complete payment. Define a store around your catalog and your customers.',to:'/services/e-commerce',icon:Workflow},{title:'Make your everyday operations more connected.',label:'BUSINESS OPERATIONS',text:'Replace disconnected records with a scoped dashboard, workflow or integration that supports how your team works.',to:'/services/business-systems',icon:BarChart3},{title:'Build an identity people recognize.',label:'BRAND EXPERIENCE',text:'Connect your logo, visual language and digital experience so customers know who they are working with.',to:'/services/branding-and-creative',icon:Code2},{title:'Plan what happens after launch.',label:'ONGOING SUPPORT',text:'Agree on updates, backups, monitoring and handover so your next chapter has a clear support plan.',to:'/services/maintenance-and-support',icon:ShieldCheck}];
export function SolutionCarousel(){const[index,setIndex]=useState(0);const item=journeys[index];return <section className="cloud-section journey-section"><div className="cloud-section-head"><div><span className="cloud-kicker">BUILT AROUND YOUR BUSINESS</span><h2>From an idea to a useful digital experience</h2><p>Explore the possibilities for your customers, your team and your next stage of growth.</p></div><div className="carousel-controls"><button aria-label="Previous solution" onClick={()=>setIndex((index+journeys.length-1)%journeys.length)}>Previous</button><span aria-live="polite">{index+1} / {journeys.length}</span><button aria-label="Next solution" onClick={()=>setIndex((index+1)%journeys.length)}>Next</button></div></div><Link to={item.to} className="journey-slide" key={index}><img className="journey-photo" src={journeyPhotos[index]} alt={journeyAlts[index]} width="1600" height="1067" loading="lazy"/><div><span className="cloud-kicker">{item.label}</span><h3>{item.title}</h3><p>{item.text}</p><span className="journey-action">Explore the solution </span></div></Link></section>}
const stages=[['Discover','Your goals, your users and your existing tools. We scope the solution and confirm the delivery approach.'],['Design','User journeys, interface layouts and your visual direction, shared for review.'],['Develop','The agreed pages, business logic and integrations take shape as a connected build.'],['Launch & support','Review, test and prepare the release, then follow the support and maintenance scope you agreed.']];
export function DeliveryExplorer(){const[stage,setStage]=useState(0);return <section className="delivery-explorer cloud-section"><div><span className="cloud-kicker">A CONNECTED DELIVERY MODEL</span><h2>Your project.<br/>From start to next.</h2><p>Direct communication, clear milestones and an agreed scope from the first conversation to handover.</p><Link to="/book-a-meeting" className="cloud-button">Book a meeting </Link></div><div className="delivery-map"><div className="delivery-line"/>{stages.map(([title],i)=><button key={title} className={i===stage?'active':''} aria-pressed={i===stage} onClick={()=>setStage(i)}><span>{String(i+1).padStart(2,'0')}</span>{title}</button>)}<Link className="delivery-stage-card" to="/process" aria-live="polite"><span className="cloud-kicker">STEP {stage+1}</span><h3>{stages[stage][0]}</h3><p>{stages[stage][1]}</p><span>See the full process </span></Link></div></section>}
