import React,{useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,Routes,Route,Link,NavLink,useLocation} from 'react-router-dom';
import {ArrowUpRight,ArrowRight,Menu,X,Globe,Check,ChevronDown,Plus,Minus,MoveUpRight,Layers,Code2,PenTool,ShieldCheck,Clock3,Mail} from 'lucide-react';
import {services,packages,faq,slug} from '../shared/catalog.js';
import Builder from './Builder.jsx';
const Login=React.lazy(()=>import('./Portal.jsx').then(m=>({default:m.Login})));
const Verify=React.lazy(()=>import('./Portal.jsx').then(m=>({default:m.Verify})));
const Portal=React.lazy(()=>import('./Portal.jsx').then(m=>({default:m.Portal})));
import {api} from './api.js';
import './styles.css';
import './premium.css';
import './cloud.css';
import {CloudHeader,CloudHome,CloudFooter} from './Cloud.jsx';
import {PremiumHome,PremiumFooter,TechnologyArt} from './Premium.jsx';

export function Button({children,to='/build',variant='',...props}){return <Link to={to} className={`button ${variant}`} {...props}>{children||'Build My Website'}<ArrowUpRight size={18}/></Link>}
export function Eyebrow({children}){return <div className="eyebrow"><span/>{children}</div>}
function Header(){const {pathname}=useLocation();return /^\/(portal|admin)(\/|$)/.test(pathname)?null:<CloudHeader/>}
function Footer(){const {pathname}=useLocation();return /^\/(portal|admin)(\/|$)/.test(pathname)?null:<CloudFooter/>}
export function BrowserArt(){return <TechnologyArt/>}
export function ServiceGrid({all=false}){return <div className="service-grid">{services.slice(0,all?services.length:6).map(([name,tagline,description],i)=><Link to={`/services/${slug(name)}`} className="service-card" key={name}><div className="service-number">{String(i+1).padStart(2,'0')}<ArrowUpRight size={22}/></div><h3>{name}</h3><p>{description}</p></Link>)}</div>}
export function PackageCards(){return <div className="package-grid">{packages.map((p,i)=><article className={`package-card ${i===1?'featured':''}`} key={p.name}><span className="small-label">{p.label}</span><h3>{p.name}</h3><p>{p.tagline}</p><div className="price">Let’s scope it.<small>Personalized quote</small></div><ul>{p.items.map(item=><li key={item}><Check size={15}/>{item}</li>)}</ul><Button to={`/build?package=${encodeURIComponent(p.name)}`} variant={i===1?'light':'secondary'}>Choose {p.name.replace('CWS ','')}</Button></article>)}</div>}
export function FAQs(){return <div className="faq-list">{faq.map(([q,a],i)=><details key={q}><summary><span className="faq-num">0{i+1}</span>{q}<Plus size={20}/></summary><p>{a}</p></details>)}</div>}
function FinalCTA(){return <section className="final-cta"><div><Eyebrow>GREAT BUSINESSES DESERVE GREAT WEBSITES</Eyebrow><h2>Let’s make<br/><em>your next move.</em></h2></div><div><p>You bring the business.<br/>We’ll bring it to life online.</p><Button variant="light"/></div><span className="cta-watermark" aria-hidden="true">↗</span></section>}
export function Home(){return <CloudHome/>}
function PageIntro({label,title,text}){const {pathname}=useLocation();const product=pathname.includes('e-commerce')||pathname==='/packages';const show=['services','work','process','about','contact','packages'].some(x=>pathname.startsWith('/'+x));return <div className={'page-intro '+(show?'page-intro-photo':'')}><div><Eyebrow>{label}</Eyebrow><h1>{title}</h1><p>{text}</p></div>{show&&<img src={product?'/images/product.jpg':pathname==='/about'?'/images/team.jpg':'/images/collaboration.jpg'} alt={product?'Product photography of a red athletic shoe':'People working together with computers'} width="1800" height="1200"/>}</div>}
function Services(){const{pathname}=useLocation();const s=services.find(v=>pathname===`/services/${slug(v[0])}`);return <><section className="section"><PageIntro label="WHAT WE DO" title={s?s[0]:<>One partner.<br/><em>Every step online.</em></>} text={s?s[2]:'Strategy, identity, design and technology. Everything your business needs, in one coordinated process.'}/>{s?<div className="detail-layout"><div><h2>{s[1]}</h2><p>Tell us where your business is today and what you want to achieve. We’ll agree the deliverables, dependencies and timeline before work begins.</p><h3>Your project includes</h3><ul className="clean-list"><li>Clear deliverables and an agreed scope</li><li>Review and feedback through your project</li><li>Final handover of the agreed work</li></ul><p>Specialist integrations and custom requirements receive a separate estimate. Service availability and ongoing costs are confirmed in your quote.</p></div><div className="side-card"><h3>Let’s talk about your project.</h3><p>Start with a brief. We’ll help shape the details.</p><Button/></div></div>:<ServiceGrid all/>}</section><FinalCTA/></>}
function Work(){return <><section className="section"><PageIntro label="WHAT WE CAN BUILD" title={<>Digital experiences.<br/><em>Real business purpose.</em></>} text="Explore the types of solutions we can scope for your business. These are capabilities, not claims of completed client projects."/><div className="solution-examples">{[['Online stores','Catalogs, checkout and connected payments.','E-commerce'],['Business dashboards','Your operations, organized in one place.','Business systems'],['Customer platforms','Bookings, accounts and services on any screen.','Web applications']].map(([title,text,service])=><Link to={'/services/'+slug(service)} className="solution-example" key={title}><TechnologyArt/><h2>{title}</h2><p>{text}</p></Link>)}</div></section><FinalCTA/></>}
function Process(){return <><section className="section"><PageIntro label="HOW FIVE HOURS WORKS" title={<>From your idea.<br/><em>To your first visitor.</em></>} text="Speed comes from clarity. A complete brief and a defined scope give us the foundation to move with purpose."/><div className="process-long">{[['01','Configure your website','Tell us about your business, the pages you need, your design preferences and any branding or content help.'],['02','Confirm the starting point','We agree the scope and quote, collect the required assets and payment, then confirm your delivery slot.'],['03','Design, build and review','Follow your project in the portal. Review deliverables and provide consolidated feedback on the specific version.'],['04','Launch and hand over','After approval and launch checks, we publish your site and provide the agreed assets and support information.']].map(([n,t,d])=><article key={n}><span>{n}</span><h2>{t}</h2><p>{d}</p></article>)}</div><div className="eligibility"><Clock3/><div><h3>What qualifies for five-hour delivery?</h3><p>Eligible standard Launch Presence and Business Growth websites with agreed scope, ready assets, required payment and a confirmed slot. The clock begins when CWS starts the build. Waiting on client decisions or extra scope changes the delivery schedule. Commerce, booking systems, marketplaces and custom applications use separate estimates.</p></div></div></section><FinalCTA/></>}
function Packages(){return <><section className="section"><PageIntro label="PACKAGES THAT FIT YOUR NEXT CHAPTER" title={<>Start with what you need.<br/><em>Build toward what’s next.</em></>} text="Choose your starting point. We’ll confirm pages, features, add-ons and pricing in a personal quote before paid work begins."/><PackageCards/><div className="add-ons"><h3>Make it your own.</h3><p>Logo design · Copywriting · Additional pages · Business email · M-Pesa integration · Booking · Advanced SEO · Monthly management</p></div></section><FinalCTA/></>}
function Contact(){const[status,setStatus]=useState(''),[busy,setBusy]=useState(false);async function submit(e){e.preventDefault();setBusy(true);setStatus('');const v=Object.fromEntries(new FormData(e.currentTarget));try{await api('/contact',{method:'POST',body:{...v,privacy:v.privacy==='on'}});setStatus('Your inquiry has been received. The CWS team will review it.');e.target.reset()}catch(e){setStatus(e.message)}finally{setBusy(false)}}return <section className="section"><PageIntro label="LET’S TALK" title={<>Good things begin<br/><em>with a conversation.</em></>} text="Have a question before you start? Send a note. For a new website, our project brief gives us the best starting point."/><div className="contact-grid"><div><h2>What are you imagining?</h2><a className="contact-phone" href="https://wa.me/254710885507">WhatsApp +254 710 885 507</a><p>A new website, a fresh identity or something more ambitious. Let’s find the right way forward.</p><Button/></div><form className="form-card" onSubmit={submit}><label>Your name<input name="name" required minLength={2} maxLength={100}/></label><label>Email<input name="email" type="email" required maxLength={254}/></label><label>Subject<input name="subject" required minLength={5} maxLength={150}/></label><label>Your message<textarea name="message" required minLength={20} maxLength={3000} rows={5}/></label><label className="check-label"><input name="privacy" type="checkbox" required/>I have read the <Link to="/privacy">privacy notice</Link>.</label><button className="button" disabled={busy}>{busy?'Sending…':'Send inquiry'}<ArrowUpRight size={18}/></button>{status&&<p role="status">{status}</p>}</form></div></section>}
function About(){return <><section className="section"><PageIntro label="CHACHA WEB SERVICES" title={<>Your ambition.<br/><em>Our attention to detail.</em></>} text="CWS brings branding, content, design, development and launch together in one productized web service."/><div className="detail-layout"><div><h2>From logo to live.</h2><p>We believe getting online should feel clear. Our guided brief turns your ideas into a structured project, with a visible process from the first design to the final handover.</p><p>Whether you need a focused business website or a custom platform, the starting point is the same: understanding your business and agreeing what success looks like.</p></div><div className="brand-display"><img src="/brand/cws-logo.png" alt="CWS — Powering digital business"/></div></div></section><FinalCTA/></>}
function Policy({terms=false}){return <section className="section prose"><Eyebrow>{terms?'SERVICE INFORMATION':'DATA HANDLING'}</Eyebrow><h1>{terms?'Before we begin.':'Your project. Your information.'}</h1><p className="notice">Pre-launch policy draft. The business owner must approve the final legal and service policies before public launch.</p>{terms?<><h2>Briefs and quotes</h2><p>Submitting a brief requests a review and quote. It does not charge you or start paid work. An accepted scope defines deliverables, revisions, payment terms and the delivery timeline.</p><h2>Delivery</h2><p>The five-hour proposition applies only to eligible standard websites once scope, assets, payment and a delivery slot are ready. Custom applications and commerce have separate timelines.</p><h2>Ownership and ongoing services</h2><p>Your quote must explain asset ownership, third-party costs, hosting renewals, maintenance, cancellation and handover before you accept.</p></>:<><h2>Information collected</h2><p>Your brief may include business and contact details, design preferences and uploaded assets. Project messages, approvals and billing records are stored to deliver the service.</p><h2>How it is used</h2><p>CWS uses this information to review your request, contact you, manage your project and provide support. Do not submit passwords or unnecessary sensitive personal information.</p><h2>Access and retention</h2><p>Project access is restricted to the verified client identity and authorized CWS administration. Uploads remain quarantined until a security scanning workflow is configured. Retention and data-request procedures require final business approval.</p></>}<Link className="text-link" to="/contact">Contact CWS <ArrowUpRight size={16}/></Link></section>}
function ScrollReset(){const {pathname}=useLocation();useEffect(()=>{window.scrollTo(0,0);document.title=`${pathname==='/'?'Websites with purpose':pathname.split('/')[1].replace(/^./,c=>c.toUpperCase())} | CWS — Chacha Web Services`;document.getElementById('main')?.focus({preventScroll:true});},[pathname]);return null;}
function App(){return <BrowserRouter><a className="skip-link" href="#main">Skip to content</a><ScrollReset/><Header/><main id="main" tabIndex={-1}><React.Suspense fallback={<section className="section"><p role="status">Opening your workspace…</p></section>}><Routes><Route path="/" element={<Home/>}/><Route path="/services/*" element={<Services/>}/><Route path="/work/*" element={<Work/>}/><Route path="/process" element={<Process/>}/><Route path="/packages" element={<Packages/>}/><Route path="/about" element={<About/>}/><Route path="/contact" element={<Contact/>}/><Route path="/faq" element={<section className="section"><PageIntro label="A LITTLE CLARITY" title="Frequently asked questions."/><FAQs/></section>}/><Route path="/build" element={<Builder/>}/><Route path="/login" element={<Login/>}/><Route path="/signup" element={<Login signup/>}/><Route path="/verify" element={<Verify/>}/><Route path="/portal/*" element={<Portal/>}/><Route path="/admin/*" element={<Portal admin/>}/><Route path="/privacy" element={<Policy/>}/><Route path="/terms" element={<Policy terms/>}/><Route path="*" element={<section className="section"><PageIntro label="404 / A SMALL DETOUR" title="This page isn’t here." text="Let’s get you back to a useful starting point."/><Button to="/">Back to home</Button></section>}/></Routes></React.Suspense></main><Footer/></BrowserRouter>}
createRoot(document.getElementById('root')).render(<App/>);
