import React,{useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,Routes,Route,Link,NavLink,useLocation,Navigate} from 'react-router-dom';
import {Menu,X,Globe,Check,ChevronDown,Plus,Minus,Layers,Code2,PenTool,ShieldCheck,Clock3,Mail} from 'lucide-react';
import {services,packages,faq,slug} from '../shared/catalog.js';
import Inquiry from './Inquiry.jsx';
import AboutPage from './About.jsx';
import {serviceDetails} from '../shared/service-details.js';
import './styles.css';
import './premium.css';
import './cloud.css';
import './brochure.css';
import {CloudHeader,CloudHome,CloudFooter} from './Cloud.jsx';
import {TechnologyArt} from './Premium.jsx';

export function Button({children,to='/build',variant='',...props}){return <Link to={to} className={`button ${variant}`} {...props}>{children||'Build My Website'}</Link>}
export function Eyebrow({children}){return <div className="eyebrow"><span/>{children}</div>}
function Header(){return <CloudHeader/>}
function Footer(){return <CloudFooter/>}
export function BrowserArt(){return <TechnologyArt/>}
export function ServiceGrid({all=false}){return <div className="service-grid">{services.slice(0,all?services.length:6).map(([name,tagline,description],i)=><Link to={`/services/${slug(name)}`} className="service-card" data-tone={i%4} key={name}><div className="service-number">{String(i+1).padStart(2,'0')}</div><h3>{name}</h3><p>{description}</p></Link>)}</div>}
export function PackageCards(){return <div className="package-grid">{packages.map(p=><Link to={`/build?package=${encodeURIComponent(p.name)}`} className="package-card featured" key={p.name}><span className="small-label">{p.label}</span><h3>{p.name}</h3><p>{p.tagline}</p><div className="price">Let’s scope it.<small>Personalized quote</small></div><ul>{p.items.map(item=><li key={item}><Check size={15}/>{item}</li>)}</ul><span className="button light">Choose {p.name}</span></Link>)}</div>}
export function FAQs(){return <div className="faq-list">{faq.map(([q,a],i)=><details key={q}><summary><span className="faq-num">0{i+1}</span>{q}<Plus size={20}/></summary><p>{a}</p></details>)}</div>}
function FinalCTA(){return <section className="final-cta"><div><Eyebrow>GREAT BUSINESSES DESERVE GREAT WEBSITES</Eyebrow><h2>Let’s make<br/><em>your next move.</em></h2></div><div><p>You bring the business.<br/>We’ll bring it to life online.</p><Button variant="light"/></div></section>}
export function Home(){return <CloudHome/>}
function PageIntro({label,title,text,image,alt}){const {pathname}=useLocation();const product=pathname.includes('e-commerce')||pathname==='/packages';const show=['services','work','process','about','contact','packages'].some(x=>pathname.startsWith('/'+x));return <div className={'page-intro '+(show?'page-intro-photo':'')}><div><Eyebrow>{label}</Eyebrow><h1>{title}</h1><p>{text}</p></div>{show&&<img src={image||(product?'/images/finance.jpg':pathname==='/about'?'/images/team.jpg':'/images/collaboration.jpg')} alt={alt||(product?'Financial planning workspace':'People working together with computers')} width="1800" height="1200"/>}</div>}
function Services(){const{pathname}=useLocation();const index=services.findIndex(v=>pathname==='/services/'+slug(v[0])),s=services[index],d=serviceDetails[index];return <><section className="section services-page"><PageIntro label="WHAT WE DO" title={s?s[0]:<>One partner.<br/><em>Every step online.</em></>} text={s?s[2]:'Strategy, identity, design and technology. Everything your business needs, in one coordinated process.'} image={d?.image} alt={d?.alt}/>{s?<div className="service-detail-layout"><div><span className="small-label">THE OPPORTUNITY</span><h2>{s[1]}</h2><p className="service-intro-copy">{d.intro}</p><h3>Who this is for</h3><p>{d.audience}</p><div className="service-scope-grid"><section><h3>What we deliver</h3><ul>{d.deliverables.map(t=><li key={t}>{t}</li>)}</ul></section><section><h3>Where it makes a difference</h3><ul>{d.uses.map(t=><li key={t}>{t}</li>)}</ul></section></div><h3>How the work takes shape</h3><ol className="service-steps">{d.process.map((t,i)=><li key={t}><b>0{i+1}</b><span>{t}</span></li>)}</ol><h3>What we need from you</h3><p>{d.inputs}</p><h3>Scope & ongoing costs</h3><p>{d.limits}</p></div><Link className="side-card service-brief-card" to={'/build?service='+encodeURIComponent(s[0])}><span className="small-label">LET’S DEFINE YOUR PROJECT</span><h3>Make {s[0].toLowerCase()} work for your business.</h3><p>Share the outcome you need. We’ll agree the scope, deliverables and quote before work starts.</p><span className="button">Start this service brief </span></Link></div>:<ServiceGrid all/>}</section><FinalCTA/></>}
function Work(){return <><section className="section"><PageIntro label="WHAT WE CAN BUILD" title={<>Digital experiences.<br/><em>Real business purpose.</em></>} text="Explore the types of solutions we can scope for your business. These are capabilities, not claims of completed client projects."/><div className="solution-examples">{[['Online stores','Catalogs, checkout and connected payments.','E-commerce'],['Business dashboards','Your operations, organized in one place.','Business systems'],['Customer platforms','Bookings, accounts and services on any screen.','Web applications']].map(([title,text,service])=><Link to={'/services/'+slug(service)} className="solution-example" key={title}><TechnologyArt/><h2>{title}</h2><p>{text}</p></Link>)}</div></section><FinalCTA/></>}
function Process(){return <><section className="section"><PageIntro label="HOW FIVE HOURS WORKS" title={<>From your idea.<br/><em>To your first visitor.</em></>} text="Speed comes from clarity. A complete brief and a defined scope give us the foundation to move with purpose."/><div className="process-long">{[['01','Tell us about your project','Tell us about your business, the pages you need, your design preferences and any branding or content help.'],['02','Confirm the starting point','We agree the scope and quote, collect the required assets and payment, then confirm your delivery slot.'],['03','Design, build and review','Review designs directly with the CWS team and share clear feedback by email or in an agreed meeting.'],['04','Launch and hand over','After approval and launch checks, we publish your site and provide the agreed assets and support information.']].map(([n,t,d])=><article key={n}><span>{n}</span><h2>{t}</h2><p>{d}</p></article>)}</div><div className="eligibility"><Clock3/><div><h3>What qualifies for five-hour delivery?</h3><p>Eligible standard Launch Presence and Business Growth websites with agreed scope, ready assets, required payment and a confirmed slot. The clock begins when CWS starts the build. Waiting on client decisions or extra scope changes the delivery schedule. Commerce, booking systems, marketplaces and custom applications use separate estimates.</p></div></div></section><FinalCTA/></>}
function Packages(){return <><section className="section"><PageIntro label="PACKAGES THAT FIT YOUR NEXT CHAPTER" title={<>Start with what you need.<br/><em>Build toward what’s next.</em></>} text="Choose your starting point. We’ll confirm pages, features, add-ons and pricing in a personal quote before paid work begins."/><PackageCards/><div className="add-ons"><h3>Make it your own.</h3><p>Logo design · Copywriting · Additional pages · Business email · M-Pesa integration · Booking · Advanced SEO · Monthly management</p></div></section><FinalCTA/></>}
function Policy({terms=false}){return <section className="section prose"><Eyebrow>{terms?'SERVICE INFORMATION':'DATA HANDLING'}</Eyebrow><h1>{terms?'Before we begin.':'Your project. Your information.'}</h1><p className="notice">Pre-launch policy draft. The business owner must approve the final legal and service policies before public launch.</p>{terms?<><h2>Briefs and quotes</h2><p>Submitting a brief requests a review and quote. It does not charge you or start paid work. An accepted scope defines deliverables, revisions, payment terms and the delivery timeline.</p><h2>Delivery</h2><p>The five-hour proposition applies only to eligible standard websites once scope, assets, payment and a delivery slot are ready. Custom applications and commerce have separate timelines.</p><h2>Ownership and ongoing services</h2><p>Your quote must explain asset ownership, third-party costs, hosting renewals, maintenance, cancellation and handover before you accept.</p></>:<><h2>Information collected</h2><p>The inquiry and meeting forms collect your name, email, optional company and phone, service interests, project requirements and preferred meeting details. Please do not include passwords or confidential files.</p><h2>How it is used</h2><p>CWS uses this information to review your request, contact you, manage your project and provide support. Do not submit passwords or unnecessary sensitive personal information.</p><h2>How forms are delivered</h2><p>This website does not offer accounts or store submissions in a CWS website database. FormSubmit processes form submissions and sends them to project@cws.com. Email correspondence is handled by CWS and its email provider. Contact CWS about access, correction or deletion of information you have shared.</p></>}<Link className="text-link" to="/contact">Contact CWS </Link></section>}
function ScrollReset(){const {pathname}=useLocation();useEffect(()=>{window.scrollTo(0,0);document.title=`${pathname==='/'?'Websites with purpose':pathname.split('/')[1].replace(/^./,c=>c.toUpperCase())} | CWS — Chacha Web Services`;document.getElementById('main')?.focus({preventScroll:true});},[pathname]);return null;}
function App(){return <BrowserRouter><a className="skip-link" href="#main">Skip to content</a><ScrollReset/><Header/><main id="main" tabIndex={-1}><Routes><Route path="/" element={<Home/>}/><Route path="/services/workflow-automation" element={<Navigate to="/services/ai-agents-and-automation" replace/>}/><Route path="/services/*" element={<Services/>}/><Route path="/work/*" element={<Work/>}/><Route path="/process" element={<Process/>}/><Route path="/packages" element={<Packages/>}/><Route path="/about" element={<AboutPage/>}/><Route path="/contact" element={<Inquiry key="contact" mode="contact"/>}/><Route path="/book-a-meeting" element={<Inquiry key="meeting" mode="meeting"/>}/><Route path="/faq" element={<section className="section"><PageIntro label="A LITTLE CLARITY" title="Frequently asked questions."/><FAQs/></section>}/><Route path="/build" element={<Inquiry key="project"/>}/>{['/login','/signup','/verify','/portal/*','/admin/*','/preview/*'].map(path=><Route key={path} path={path} element={<Navigate to="/contact" replace/>}/>)}<Route path="/privacy" element={<Policy/>}/><Route path="/terms" element={<Policy terms/>}/><Route path="*" element={<section className="section"><PageIntro label="404 / A SMALL DETOUR" title="This page isn’t here." text="Let’s get you back to a useful starting point."/><Button to="/">Back to home</Button></section>}/></Routes></main><Footer/></BrowserRouter>}
createRoot(document.getElementById('root')).render(<App/>);
